name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests"
      - name: Run Test2
        run: echo "Running Test2"
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests"
      - name: Run Test2
        run: echo "Running Test2"
    
  test3:
    needs: test1
    runs-on: ubuntu-latest # gtihub hosted runner
    steps:
      - name: Get the code
        uses: actions/checkout@v4 # action checkout
      - name: Run tests
        run: python --version
      - name: check python3
        run: python3 --version

  test4:
    needs: [test3, test2]
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run tests
        run: python --version
      - name: install numpy
        run: pip install numpy
      - name: check python3
        run: python3 mathematical_operation.py
    